package pro.vinyard.dofus.map.helper.model;

import java.util.HashMap;

public class IndiceListModel  {
	
	private static final HashMap<Integer, String> indicesMap = new HashMap<Integer, String>() {
		private static final long serialVersionUID = 1L;
	{
		put(100,"Citrouille");
		put(101,"Brouette de citrouilles");
		put(102,"Râteau");
		put(103,"Fourche");
		put(104,"Silo vide");
		put(105,"Caisse");
		put(106,"Caisse explosive");
		put(107,"Poubelle");
		put(108,"Ancre");
		put(109,"Etendoir à linge");
		put(110,"Banc");
		put(111,"Seau plein");
		put(112,"Seau vide");
		put(113,"Roseaux");
		put(114,"Chariot de mineur");
		put(115,"Charrette");
		put(116,"Chariot");
		put(117,"Chariot de Cawottes");
		put(118,"Rondelles de Cawottes");
		put(120,"Puits");
		put(121,"Bijoux de famille");
		put(122,"Objet de désir");
		put(123,"Bûbche phallique");
		put(124,"Drapeau Wabbit");
		put(125,"Chaise de plage");
		put(130,"Epouvantail");
		put(131,"Epouvantail");
		put(132,"Hache");
		put(133,"Pont en pierre");
		put(135,"Boîte aux lettres");
		put(136,"Echelle");
		put(138,"Ossements");
		put(139,"Crâne de Dragon");
		put(140,"Arc");
		put(141,"Flèche");
		put(142,"Botte");
		put(143,"Panneau avec tête de mort");
		put(145,"Totem");
		put(146,"Transporteur");
		put(147,"Corbac");
		put(148,"Oiseau noir");
		put(150,"Volatile sombre");
		put(151,"Statue Koalak");
		put(152,"Statue de classe");
		put(155,"Statue cyclope");
		put(156,"Tombe");
		put(157,"Tombe Koalak");
		put(158,"Statue Dragodinde");
		put(159,"Statue Dragodinde éteinte");
		put(160,"Statue Dragodinde allumée");
		put(161,"Statue Dragodinde sans socle");
		put(162,"Feuilles de papier");
		put(163,"Oiseau aux yeux globuleux");
		put(164,"Volatile aux yeux globuleux");
		put(166,"Bouclier");
		put(168,"Bouclier de Pandala");
		put(169,"Bouclier cochon");
		put(170,"Bouclier Iop");
		put(171,"Bouclier Wabbit");
		put(172,"Bouclier croissant de lune");
		put(173,"Bouclier en peau noire et blanche");
		put(174,"Bouclier barré");
		put(175,"Bouclier étoilé");
		put(176,"Bouclier à anneaux");
		put(177,"Bouclier à cornes");
		put(178,"Bouclier à pointes");
		put(179,"Bouclier gelé");
		put(180,"Epouvantail Minotoror");
		put(181,"Paille");
		put(182,"Stèle");
		put(183,"Stèle en bois");
		put(184,"Stèle en pierre");
		put(185,"Panneau de pêcheur");
		put(186,"Caisse de pain");
		put(187,"Sac rapiécé");
		put(188,"Masse enfoncée dans le sol");
		put(189,"Trident planté");
		put(195,"Bernard-l'ermite");
		put(196,"Charrette de laine de Bouftou");
		put(197,"Charrette mordillée");
		put(198,"Charrette géante en bois");
		put(199,"Charrette géante en bois vide");
		put(200,"Charrette géante en bois pleine");
		put(201,"Attelage de Bouftous");
		put(202,"Roue en bois");
		put(203,"Entrée de mine en bois");
		put(204,"Objet flottant");
		put(205,"Bouteille flottante");
		put(206,"Tofu flottant");
		put(207,"Chapeau flottant");
		put(208,"Sac flottant");
		put(209,"Seau flottant");
		put(210,"Sac flottant");
		put(211,"Sac flottant");
		put(212,"Volatile flottant");
		put(214,"Balai");
		put(215,"Puits couvert");
		put(216,"Puits tâché");
		put(217,"Puits non couvert");
		put(218,"Cadavre calciné");
		put(219,"Dépouille brûblée");
		put(220,"Totem de Moon couché");
		put(221,"Papillon");
		put(222,"Rocher Bouftou");
		put(223,"Squelette d'humanoïde assis");
		put(224,"Squelette d'humanoïde poignardé");
		put(225,"Squelette d'humanoïde allongé");
		put(226,"Squelette d'humanoïde suppliant");
		put(227,"Squelette de Dragodinde");
		put(228,"Squelette d'humanoïde");
		put(229,"Colonne vertébrale imposante");
		put(230,"Squelette de Dragon");
		put(231,"Patte de Dragon");
		put(232,"Aile de Dragon squelettique");
		put(234,"Porte avec quatre troncs");
		put(235,"Fontaine");
		put(236,"Planche de glisse");
		put(237,"Rafiot");
		put(238,"Chaloupe");
		put(239,"Chaudière");
		put(240,"Caisse de fruits rouges");
		put(241,"Totem Kanniboul joyeux");
		put(242,"Totem Kanniboul triste");
		put(243,"Totem Kanniboul colérique");
		put(244,"Totem Kanniboul cornu");
		put(245,"Roulotte");
		put(246,"Bouée");
		put(247,"Catapulte");
		put(248,"Séchoir à viande");
		put(249,"Brochette de Tofu");
		put(250,"Tour de guet");
		put(251,"Cible");
		put(252,"Scaphandre");
		put(253,"Robinet");
		put(254,"Lanterne");
		put(255,"Astrolabe sphérique");
		put(257,"Coffre");
		put(258,"Totem Bouftou en bois");
		put(259,"Phare");
		put(26,"Statue Ecaflip");
		put(260,"Panneau d'enclos");
		put(261,"Tofu mort");
		put(262,"Cage");
		put(263,"Statue Pandawa guérisseur");
		put(264,"Statue Pandawa en chocolat");
		put(265,"Paquet Pandawa");
		put(266,"Piquet en bois");
		put(267,"Distributeur de liqueur");
		put(27,"Phénix");
		put(270,"Crustacé");
		put(271,"Coquillage et sa perle");
		put(272,"Anémone");
		put(273,"Grande plaque verticale en pierre");
		put(274,"Tonneau");
		put(275,"Jarre");
		put(276,"Champignon");
		put(277,"Pilier en pierre");
		put(278,"Squelette de Boufmouth");
		put(279,"Canon");
		put(28,"Statue Crâ");
		put(280,"Statue Lenald");
		put(281,"Statue Lenald décapitée");
		put(282,"Tente");
		put(283,"Tente de Sanglier");
		put(284,"Tente cornue de Sanglier");
		put(285,"Tente de Mulou");
		put(286,"Tente cornue de Mulou");
		put(287,"Boîte à outils");
		put(288,"Tente en cours de construction");
		put(29,"Statue Eniripsa");
		put(290,"Pot d'huile");
		put(291,"Boîte à outils");
		put(292,"Bottes suspendues");
		put(293,"Traineau");
		put(294,"Traineau piloté par un Mansot");
		put(295,"Traineau détruit");
		put(296,"Traîneau rempli de bois");
		put(297,"Traineau recouvert d'une couverture");
		put(298,"Traineau avec un coussin");
		put(299,"Panneau avec 3 directions");
		put(30,"Statue Enutrof");
		put(300,"Panneau \"Chute de pierres\"");
		put(301,"Tapis en peau de monstre");
		put(302,"Trio de tonneaux");
		put(303,"Planches contre deux caisses");
		put(304,"Caisses empilées cachées par des planches");
		put(305,"Sapin en filet");
		put(306,"Créature gelée");
		put(307,"Kaniglou gelé");
		put(308,"Mansot gelé");
		put(309,"Mansot et son poisson gelés");
		put(31,"Statue Féca");
		put(310,"Kaniglou et sa cawotte gelés");
		put(311,"Mansot et son poisson et sa cawotte gelés");
		put(312,"Mansot et sa cawotte gelés");
		put(313,"Kaniglou et sa coiffe de glace");
		put(314,"Mansot et sa coiffe de glace");
		put(315,"Manomètre");
		put(317,"Caisse de pêcheur");
		put(318,"Tonneau de poisson");
		put(319,"Filet de fruits");
		put(32,"Statue Iop");
		put(320,"Tas de planches avec une hache");
		put(321,"Pelle");
		put(322,"Poisson qui cuit");
		put(323,"Tonneau couché");
		put(324,"Tonneau couché avec robinet");
		put(325,"Coffre cadenassé");
		put(326,"Coffres cadenassés superposés");
		put(328,"Grue");
		put(329,"Fagots de branches");
		put(33,"Statue Osamodas");
		put(330,"Rondin de bois");
		put(331,"Tube ouvert");
		put(332,"Tube d'alchimiste");
		put(334,"Tube fermé");
		put(335,"Charrette avec un ballot de paille");
		put(336,"Barre de métal courbée");
		put(337,"Statue décapitée");
		put(338,"Cloche");
		put(34,"Statue Sadida");
		put(340,"Croix tombale");
		put(342,"Fumerolle");
		put(343,"Fumerolle bouchée");
		put(344,"Fumerolle à bulles");
		put(345,"Source chaude");
		put(346,"Machine à vapeur");
		put(347,"Tripode à vapeur");
		put(348,"Panneau \"Volcan\"");
		put(349,"Caisse prise dans la neige");
		put(35,"Statue Sram");
		put(350,"Engrenage");
		put(351,"Lampadaire");
		put(352,"Coffre pris dans la neige");
		put(353,"Tonneau pris dans la neige");
		put(358,"Caisse cachée par une planche");
		put(359,"Bloc de glace suspendu");
		put(36,"Statue Xélor");
		put(360,"Traineau pris dans la neige");
		put(361,"Banque");
		put(363,"Arbre calciné couché");
		put(366,"Dessin de Koalak");
		put(367,"Seau de peinture");
		put(368,"Canne à pêche plantée dans une caisse");
		put(369,"Voleur de coquille");
		put(37,"Statue Sacrieur");
		put(370,"Pagure");
		put(371,"Squelette de matelot pirate");
		put(373,"Squelette de capitaine pirate");
		put(374,"Squelette de pirate sur un tonneau");
		put(375,"Barre");
		put(376,"Voile pirate");
		put(377,"Bateau détruit");
		put(378,"Oeuf");
		put(379,"Oeuf de volatile cassé");
		put(38,"Statue à queue pointue");
		put(382,"Oeuf dans son nid");
		put(383,"Oeuf avec marmaille");
		put(384,"Cocktail");
		put(385,"Pagaie");
		put(386,"Bâton avec une corde");
		put(387,"Mangeoire");
		put(389,"Cocktail");
		put(39,"Statue Pandawa");
		put(394,"Oeuf de Dragoeuf");
		put(395,"Oeuf de volatile");
		put(396,"Oeuf de Dragoeuf enfoui");
		put(397,"Oeuf de Dragoeuf cassé");
		put(398,"Oeuf surprise");
		put(399,"Tonneau de tentacules");
		put(40,"Statue Zobal");
		put(400,"Etalage de poisson");
		put(401,"Poisson suspendu");
		put(402,"Poisson accroché par la queue");
		put(403,"Poisson avec la tête en bas");
		put(404,"Étendard");
		put(405,"Etendard avec des os");
		put(406,"Etendard avec un seul os");
		put(407,"Etendard feuillu");
		put(408,"Dessin");
		put(409,"Dessin de Bwork");
		put(41,"Statue Steamer");
		put(414,"Ciseaux et peigne");
		put(415,"Bouftou suspendu");
		put(416,"Viande de Bouftou accrochée");
		put(417,"Fenêtre avec tissu");
		put(418,"Seau de sable");
		put(419,"Coquillage rayé");
		put(42,"Statue Lhambadda");
		put(420,"Affiche");
		put(421,"Affiche de monstre");
		put(422,"Affiche de crabe");
		put(423,"Affiche de nourriture");
		put(424,"Crabe effrayant");
		put(425,"Monstre marin");
		put(426,"Monstre des profondeurs");
		put(427,"Affiche de bateau");
		put(428,"Piston");
		put(429,"Menhir");
		put(43,"Panneau de Kerubim");
		put(430,"Cible d'un archer talentueux");
		put(431,"Cible d'un archer confirmé");
		put(434,"Cible d'un archer débutant");
		put(435,"Tente cornue de Mulou fléché");
		put(436,"Coffre enfoui");
		put(437,"Charrette cassée");
		put(438,"Observateur furtif");
		put(439,"Bombarde");
		put(44,"Planche");
		put(440,"Longue vue");
		put(441,"Trappe");
		put(442,"Trappe sombre");
		put(443,"Trappe sombre à 9 trous");
		put(444,"Trappe sombre à 16 trous");
		put(445,"Trappe lumineuse");
		put(446,"Trappe lumineuse à 9 trous");
		put(447,"Trappe lumineuse à 16 trous");
		put(448,"Bobine encordée");
		put(449,"Rouleau de métal posé sur la tranche");
		put(450,"Robot");
		put(451,"Géant de fer");
		put(452,"Robot avec une pince");
		put(453,"Robot avec 2 yeux");
		put(454,"Robot cassé");
		put(455,"Visse géante");
		put(456,"Jardinière");
		put(457,"Jardinière carrée");
		put(458,"Jardinière en engrenage");
		put(459,"Jardinière en double engrenage");
		put(46,"Abreuvoir en pierre");
		put(460,"Drapeau du Comte");
		put(461,"Baliste");
		put(462,"Cible en paille");
		put(463,"Quintaine");
		put(464,"Quintaine Minotoror");
		put(465,"Minotoror");
		put(466,"Quintaine épouvantail");
		put(467,"Epouvantail");
		put(468,"Ratelier d'armes");
		put(469,"Epée");
		put(47,"Sac");
		put(470,"Epée prise dans la neige");
		put(472,"Barricade");
		put(473,"Main");
		put(474,"Etendard de cordonnier");
		put(475,"Tonneau rempli de lannières de cuir");
		put(476,"Rouleau de tissu");
		put(477,"Tête de Dragon Cochon");
		put(478,"Deux grosses défenses");
		put(479,"Groin de dragon");
		put(48,"Panneau");
		put(480,"Pomme fourrée");
		put(481,"Entrée d'égoûbts");
		put(482,"Entrée malodorante");
		put(483,"Echelle cassée");
		put(484,"Sac suspendu");
		put(485,"Seau d'arêtes");
		put(486,"Main de monstre");
		put(487,"Planches suspendues");
		put(488,"Grande bière");
		put(489,"Rouleau de métal");
		put(49,"Statue");
		put(490,"Rouleau de métal accroché");
		put(491,"Tête de mort en pavés");
		put(492,"Tofu épinglé");
		put(493,"Statue impressionante");
		put(496,"Monture de pierre");
		put(497,"Pierre précieuse");
		put(498,"Maillons");
		put(499,"Chaîne");
		put(500,"Panneau \"Alchimistes\"");
		put(501,"Panneau \"Bijoutiers\"");
		put(502,"Panneau \"Bricoleurs\"");
		put(503,"Panneau \"Boulangers\"");
		put(504,"Panneau \"Forgerons\"");
		put(505,"Panneau \"Tailleurs\"");
		put(506,"Panneau \"Bouchers\"");
		put(507,"Panneau \"Sculpteurs\"");
		put(508,"Panneau \"Bûbcherons\"");
		put(509,"Panneau \"Eleveurs\"");
		put(510,"Casque");
		put(511,"Peau étendue");
		put(512,"Peau de Fricochère");
		put(513,"Peau de Givrefoux");
		put(514,"Tas de peaux");
		put(515,"Plan de bricolage");
		put(516,"Affiche de bricolage");
		put(517,"Armure");
		put(518,"Epaulière");
		put(519,"Casque à plume");
		put(520,"Casque à visière");
		put(521,"Wabbit peintre");
		put(522,"Wabbit endormi");
		put(523,"Wabbit pêcheur");
		put(524,"Wo Wabbit endormi");
		put(525,"Wabbits perchés");
		put(526,"Foreuse Wabbit");
		put(527,"Foreuse plantée");
		put(528,"Etendard Bouftou");
		put(529,"Rouleau de laine");
		put(53,"Outil");
		put(530,"Sac de laine");
		put(531,"Bouftou mort");
		put(532,"Cible Bouftou");
		put(533,"Blason en peau");
		put(534,"Masse");
		put(535,"Marteau-piqueur");
		put(536,"Tonneau de peinture");
		put(537,"Pinceau usagé");
		put(538,"Pierres suspendues");
		put(539,"Blason Kanigroula");
		put(540,"Blason Kanigrou");
		put(541,"Blason trace de patte");
		put(542,"Blason ossements");
		put(543,"Blason longues dents");
		put(544,"Pendentif de sorcière");
		put(545,"Cabane en bois");
		put(546,"Cabane avec plancher");
		put(547,"Cabane avec porte en toile");
		put(548,"Cabane avec boîte aux lettres");
		put(549,"Cabane avec toit en toile");
		put(55,"Pince");
		put(550,"Cabane sans plancher");
		put(551,"Cabane sans toit");
		put(552,"Totem avec des bois");
		put(553,"Citrouille perchée");
		put(554,"Arbre bonbon");
		put(555,"Chasse-neige");
		put(556,"Écharpe");
		put(557,"Moulin");
		put(559,"Support d'ailes de moulin");
		put(56,"Canne à pêche");
		put(560,"Moulin sans toit");
		put(561,"Caisse d'outils");
		put(562,"Bouteille");
		put(563,"Chapeau");
		put(564,"Coiffe");
		put(565,"Couvre-chef");
		put(566,"Dora Bora");
		put(567,"Coiffe du Bouftou");
		put(568,"Coiffe du Bouftou royal");
		put(569,"Krokop");
		put(57,"Attrape poisson");
		put(570,"Le Floude");
		put(571,"Casque de Maître Nabur");
		put(572,"Chapeau du marié");
		put(573,"Couronne du roi Gelax");
		put(574,"Casque pour l'île de Moon");
		put(575,"Casque Citrouille");
		put(576,"Bandeau");
		put(577,"Chapeau à plume");
		put(578,"Branche cassée");
		put(579,"Ecoulement de sève");
		put(58,"Tonnelle");
		put(580,"Seau suspendu");
		put(581,"Epée plantée");
		put(582,"Peluche Koalak");
		put(583,"Dessin de Dragodinde");
		put(584,"Trace de griffes");
		put(585,"Fissure");
		put(586,"Rocher fendu");
		put(587,"Arbre creux");
		put(588,"Arbre à feuilles trouées");
		put(589,"Plante épineuse");
		put(59,"Abri en toile");
		put(590,"Plante carnivore");
		put(592,"Plante tentaculaire");
		put(593,"Plante pomme de pin");
		put(594,"Souche avec un champignon");
		put(595,"Rocher sacrificiel");
		put(596,"Arbre à lanterne");
		put(597,"Arbre rempli de crânes");
		put(598,"Arbre transpercé");
		put(599,"Fleur verte");
		put(600,"Fleur bleue");
		put(601,"Dalle en forme de Kama");
		put(602,"Tonneau rempli d'outils");
		put(603,"Chariot à vapeur");
		put(604,"Sac de Kamas");
		put(605,"Sac de Kamas éventré");
		put(606,"Chariot rempli d'or");
		put(608,"Sac de Kamas noué");
		put(609,"Coffre moustachu");
		put(610,"Coffre moustachu enfoui");
		put(611,"Chariot de pierres");
		put(612,"Pierre triangulaire");
		put(613,"Globe étoilé");
		put(614,"Coffre d'amour");
		put(615,"Dragon en or");
		put(618,"Queue de dragon");
		put(619,"Tonneau de Kamas");
		put(620,"Statue de Centaure");
		put(621,"Bac de laine");
		put(622,"Dessin de Koalak armé");
		put(623,"Dessin de squelette Koalak");
		put(624,"Lance plantée");
		put(625,"Panneau \"Os\"");
		put(626,"Os en bois");
		put(627,"Trou");
		put(628,"Pierre taillée");
		put(629,"Masse d'armes végétale");
		put(630,"Fleur spiralée");
		put(631,"Rocher sculpté");
		put(632,"Corbac écrasé");
		put(633,"Rocher troué");
		put(634,"Os dessiné");
		put(636,"Arche rocheuse");
		put(637,"Plante éventail");
		put(638,"Seau renversé");
		put(639,"Tofu enfourché");
		put(64,"Abreuvoir");
		put(640,"Panneau \"Fonderie\"");
		put(641,"Seau de pierres précieuses");
		put(642,"Tonneau ficelé");
		put(643,"Bateau échoué");
		put(644,"Bateau en papier");
		put(645,"Bocal");
		put(646,"Bitte d'amarrage");
		put(647,"Barque renversée");
		put(648,"Rafiot renversé");
		put(649,"Chaloupe renversée");
		put(65,"Abreuvoir en bois");
		put(650,"Barque avec une étoile");
		put(651,"Rafiot avec une étoile");
		put(652,"Chaloupe avec une étoile");
		put(653,"Charette de céréales");
		put(654,"Tracteur");
		put(655,"Statue de faucheur");
		put(656,"Sac de charbon");
		put(657,"Viande suspendue");
		put(658,"Saucisse suspendue");
		put(659,"Souche avec des petites pousses");
		put(66,"Marteau");
		put(660,"Jouet Tofu");
		put(661,"Jouet Bouftou");
		put(662,"Arbre à Chacha");
		put(663,"Griffoir");
		put(664,"Roulotte cassée");
		put(665,"Roulotte transpercée");
		put(666,"Panier d'oeufs");
		put(667,"Flèche cassée");
		put(668,"Feu de camp");
		put(669,"Aventurier gelé");
		put(67,"Etoile de mer");
		put(670,"Palette en bois");
		put(671,"Cawotte plantée");
		put(672,"Coquillage conique");
		put(673,"Coquillage spiralé");
		put(674,"Caisse de boucher");
		put(675,"Zaapi");
		put(676,"Ballon");
		put(677,"Serviette de plage");
		put(678,"Cadeau");
		put(680,"Os pris dans la glace");
		put(681,"Tube feuillu");
		put(682,"Caisse de coraux");
		put(683,"Carton");
		put(684,"Rondins de bambou");
		put(686,"Jarre ouverte");
		put(687,"Jarre fermée");
		put(688,"Tonneau explosif");
		put(689,"Tonneau flottant");
		put(690,"Flèche plantée dans le sol");
		put(691,"Champignon luminescent");
		put(692,"Caisse flottante");
		put(693,"Bombe");
		put(694,"Lance");
		put(695,"Porte-manteau");
		put(696,"Panneau d'affichage");
		put(697,"Sac de Tofus");
		put(698,"Torche");
		put(699,"Chaîne mouillée");
		put(70,"Etoile de mer avec un oeil");
		put(702,"Porte de cave");
		put(703,"Réservoir");
		put(704,"Chacha noir");
		put(705,"Pieu avec des os");
		put(706,"Pot en forme de crâne");
		put(707,"Panneau étoilé");
		put(708,"Poisson toxique");
		put(709,"Barque au mât cassé");
		put(71,"Duo d'étoiles de mer");
		put(710,"Panneau couvert");
		put(711,"Ballon accroché");
		put(712,"Chariot à viande");
		put(713,"Crâne cornu sur un piquet");
		put(714,"Panneau avec un oeil");
		put(715,"Citerne");
		put(716,"Château d'eau");
		put(717,"Noix de Kokoko ouverte");
		put(718,"Volatile squelette");
		put(719,"Squelette d'humanoïde empalé");
		put(72,"Sac de farine");
		put(720,"Scie");
		put(721,"Trace d'ours");
		put(722,"Lampadaire en os");
		put(723,"Tonneau porté");
		put(724,"Citrouille gelée");
		put(725,"Cawotte gelée");
		put(726,"Drapeau de Vulkania");
		put(727,"Chaudron");
		put(728,"Soutien-gorge");
		put(729,"Tas de fourrures");
		put(73,"Sac de boulanger");
		put(730,"Squelette sur un banc");
		put(731,"Cible en forme de maison");
		put(732,"Sous-vêtement");
		put(733,"Culotte");
		put(734,"Affiche de tortue");
		put(735,"Epée ensanglantée");
		put(736,"Barge");
		put(737,"Croix lumineuse");
		put(738,"Crâne de Givrefoux");
		put(739,"Banc cassé");
		put(74,"Arrosoir");
		put(740,"Crâne peint");
		put(741,"Caisse d'engrenages");
		put(742,"Chariot de mineur renversé");
		put(743,"Centrale thermique");
		put(744,"Cible en paille sur roulettes");
		put(746,"Sac de bonbons");
		put(747,"Ballon Tofu");
		put(748,"Ballon Bouftou");
		put(749,"Boîte à outils");
		put(75,"Seau");
		put(750,"Boîte de pizzas");
		put(751,"Fosse commune");
		put(752,"Chevalet");
		put(753,"Chariot rempli de charbon");
		put(754,"Roulotte à jouets");
		put(755,"Bestiole géante en bois");
		put(756,"Chaise de maître nageur");
		put(757,"Voiture en bois");
		put(758,"Arrosoir mécanique");
		put(759,"Bougeoir en forme de crâne");
		put(76,"Seau de forgeron");
		put(760,"Toilettes");
		put(761,"Téléscope");
		put(762,"Charrette à deux roues");
		put(763,"Charrette à 4 roues");
		put(764,"Lance avec des os");
		put(765,"Réservoir d'eau");
		put(766,"Enclume");
		put(767,"Drapeau en slip");
		put(768,"Statue avec des dagues");
		put(769,"Caisse mystère");
		put(77,"Barque");
		put(770,"Caisse médicale");
		put(771,"Seringue géante");
		put(772,"Flamèche sur un ponton");
		put(773,"Tronc creux couché");
		put(774,"Roue à aube");
		put(775,"Chacha pris dans une toile");
		put(776,"Tombe en bois");
		put(777,"Grand coquillage");
		put(778,"Wabbit gelé");
		put(779,"Piège");
		put(780,"Cercueil en bois");
		put(781,"Broyeur");
		put(782,"Statue qui pleure");
		put(783,"Squelette de poisson");
		put(86,"Pioche");
		put(87,"Souche qui ne repousse pas");
		put(89,"Brouette");
		put(90,"Eolienne");
		put(905,"Poupée");
		put(906,"Feu éteint");
		put(907,"Tente de foire");
		put(908,"Pot en ossements");
		put(909,"Guirlande d'os");
		put(91,"Silo");
		put(910,"Statue Roublard");
		put(911,"Statue Huppermage");
		put(912,"Amphore");
		put(913,"Champignon sur un arbre");
		put(914,"Tombe ouverte");
		put(915,"Cerceuil enfoui");
		put(916,"Tambour");
		put(917,"Roulotte carbonisée");
		put(918,"Roulotte brûblée");
		put(919,"Roulotte fumante");
		put(92,"Ballot de paille");
		put(920,"Statue de crabe");
		put(921,"Squelette de Droupik");
		put(922,"Caisse cassée");
		put(923,"Coffre recouvert de mousse");
		put(924,"Chacha noir assommé");
		put(925,"Cage avec une goule");
		put(926,"Tente détruite");
		put(927,"Tonneau détruit");
		put(928,"Tonneau enfoui");
		put(929,"Roulotte laboratoire");
		put(93,"Ballot de paille sur une charrette");
		put(930,"Roulotte enfouie");
		put(931,"Borne");
		put(932,"Borne enfouie");
		put(933,"Squelette de mineur");
		put(934,"Goule empalée");
		put(935,"Fontaine sanguinolente");
		put(936,"Goule pendue");
		put(937,"Squelette d'humanoïde encordé");
		put(938,"Likrone");
		put(939,"Goule coincée");
		put(94,"Parasol");
		put(940,"Butoir en os");
		put(941,"Tombe Ouginak");
		put(942,"Statue Ouginak");
		put(943,"Monocycle");
		put(944,"Pyramide d'os");
		put(945,"Canon en bois");
		put(946,"Ballon crapaud");
		put(947,"Ballon Dragodinde");
		put(948,"Roulotte fongique");
		put(949,"Statue d'Ougah");
		put(950,"Statue de champignon");
		put(951,"Statue fongique");
		put(952,"Champignon en pierre");
		put(953,"Os avec un boulet");
		put(954,"Echelle en os");
		put(955,"Coffre porté par un Pandawa");
		put(956,"Pompe géante");
		put(957,"Bicyclette");
		put(958,"Piège à mâchoire");
		put(959,"Statue avec un trident");
		put(960,"Peau d'Ecaflip");
		put(961,"Peau de Kanigrou");
		put(962,"Tuyau géant");
		put(99,"Nichoir de Piou");

	}};
	
	public static String getIndiceName(int indice) {
		return IndiceListModel.indicesMap.get(indice);
	}

}
